apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: disks.samplecrd.k8s.io
spec:
  group: samplecrd.k8s.io
  version: v1
  #CR资源名字教Network
  names:
    kind: Disk
    plural: disks
  #类似pod
  scope: Namespaced
